version: "3.5"
services:
    probe:
        build: docker
        env_file: docker/environment
        volumes:
            - ./src:/probe
        command: python /probe/probe.py
        network_mode: host
        labels:
            - amf=1111
