version: "3.5"
services:
    probe:
        build: docker
        env_file: docker/environment
        volumes:
            - ./src:/probe
        command: python /probe/main.py
        network_mode: host
