version: "3.5"
services:
    probe:
        build: .
        volumes:
            - ./config/probe.yml:/probe/config/probe.yml
        command: python /probe/probe.py --config config/probe.yml
        network_mode: host